# Generated by Django 5.0.1 on 2024-01-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='poster',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
