# Generated by Django 5.0.1 on 2024-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/')),
                ('course', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1)),
                ('material_type', models.CharField(choices=[('Notes', 'Notes'), ('PYQ', 'Previous Year Questions')], default='Notes', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='Year',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
