# Generated by Django 5.0.1 on 2024-03-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('image', models.ImageField(default='path/to/placeholder/image.jpg', upload_to='events/')),
                ('date', models.DateField(default='2002-04-01')),
            ],
        ),
    ]
