# Generated by Django 5.0.1 on 2024-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDash', '0002_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
