# Generated by Django 5.0.1 on 2024-03-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDash', '0003_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('material_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='study_materials/')),
            ],
        ),
    ]
